### ISSUE TITLE
Bookdown

### ISSUE THREAD

**Issue by rosstox26** [evannasu/MBAn501-Team-Even-Better#1]
As a priority task, you would want to install the Bookdown package and create the demo bookdown "book" - you will then be able to edit the demo book to create your content.

**Comment by rosstox26** [comment]
Any update folks?

**Comment by evannasu** [comment]
Thank you for your advice. I have uploaded a bookdown package and added several RMD files. Then we will update the INTRO and ABOUT US part. After that, we will update the TOC.

**Comment by lidaz3** [comment]
We seemed to only be able to build a new bookdown project using git in a sub-folder. I wonder what do you mean by installing the Bookdown package in the root loacation?

**Comment by rosstox26** [comment]
This is the folder structure I am looking for: https://github.com/Ameybhile/MBAn_Career_Handbook

Bookdown is installed in the root folder, there is then a docs folder where your published material lives.

**Comment by lidaz3** [comment]
Got it. I manually moved our sub directory to the root. And our "doc folder" is called "_book". Is this OK now?

**Comment by rosstox26** [comment]
The output folder has to be named "docs". See the last line of this file: https://github.com/nklobo-mban/EffectiveCommunication/blob/main/_bookdown.yml

Then you can go to settings -> pages and set the pages location to main branch and docs folder. Then you should be able to see your published site.

**Comment by evannasu** [comment]
I changed the branch. And an error appears:
''' Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss': No such file or directory @ dir_chdir - /github/workspace/docs'''

**Comment by rosstox26** [comment]
The output folder has to be called "docs". You need to make the following change for it to be created.

See the last line of this file: https://github.com/nklobo-mban/EffectiveCommunication/blob/main/_bookdown.yml

**Comment by evannasu** [comment]
We think it works now!! Thank you so much.
https://evannasu.github.io/MBAn501-Team-Even-Better/
Then we will continue to update content. @lidaz3 @Z-ynnnn @yangbei99 @nilsaileana

**Comment by rosstox26** [comment]
Yup - looks good now. well done.
